services:
  db:
    container_name: mobile_db
    image: docker.arvancloud.ir/postgres:17-alpine
    restart: always
    env_file: "postdb.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${POSTDB_PASSWORD}
      - POSTDB_NAME=${POSTDB_NAME}
      - POSTDB_USER=${POSTDB_USER}
    healthcheck:
      test: ["CMD", "pg_isready -U postgres -d ${POSTDB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    env_file: ".env"
    container_name: django
    volumes:
      - static_files:/home/app/staticfiles
    build:
      context: .
      dockerfile: dockerfile/prod/Dockerfile
    restart: always
    expose:
      - 8000
    ports:
      - "8000:8000"

  redis:
    container_name: education_mobile_redis
    image: docker.arvancloud.ir/redis:8.2-alpine
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    container_name: education_mobile_nginx
    build:
      context: .
      dockerfile: dockerfile/prod/nginx/Dockerfile
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static_files:/var/www/static
      - /etc/letsencrypt:/etc/letsencrypt:ro
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  static_files:
  postgres_data:
